[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

upload_port = COM5
monitor_port = COM5

monitor_speed = 115200

lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    tzapu/WiFiManager @ ^2.0.5
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
